### PR TITLE
templatize migrations: apply patch from pr #793

### PR DESCRIPTION
**Pull request by dhawal1248**

### CODE REVIEW

**Review by srikanthccv — APPROVED** [review]
LGTM

**Comment by srikanthccv** [comment]
I just realised you changed the module name here: https://github.com/SigNoz/golang-migrate/pull/1/commits/3ecfdf8f71772b10066cbebb621cab431cc91bb0. Usually, we don't do that. Instead, we use the replace directive i.e `github.com/golang-migrate/migrate/v4 => github.com/SigNoz/migrate/v4 vx.y.z.` Is there a reason why you changed the module name?

**Comment by nityanandagohain** [comment]
We are only adding changes from this PR right https://github.com/golang-migrate/migrate/pull/793 right ?

**Comment by dhawal1248** [comment]
@srikanthccv we are using the replace directive as you mentioned..but how does the replace derective know where to find the new module if we dont change the module name here?

**Comment by dhawal1248** [comment]
> We are only adding changes from this PR right [golang-migrate#793](https://github.com/golang-migrate/migrate/pull/793) right ?

This and one more patch, on pr #2

**Comment by srikanthccv** [comment]
That's the entire work of replace directive. For instance, we have a fork for Prometheus here: https://github.com/SigNoz/prometheus/ and replace directive here: https://github.com/SigNoz/signoz/blob/321cba2af5c8b9ee568753def939c440cddd79e7/go.mod#L188. The import path we use will still be `github.com/golang-migrate/migrate/v4`. You don't need to change the module if you are going to use the replace directive. Let me know if it's not clear.

**Comment by dhawal1248** [comment]
@srikanthccv got it..i was under the impression that only the git path is not enough..go.mod should also have the updated path
but looks like that is not required 👍

**Comment by srikanthccv** [comment]
Other than that, the PR looks good to me.

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
